name: atomic_design_system
description: "Un sistema de diseño en Flutter basado en los principios Atomic Design"
version: 0.0.1
homepage: https://github.com/Marisolperez22/atomic_desing_system.git

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 700    
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600  

